CS-C-BDD-TDD/human-review-backend

pom.xml

DHS-53 Updated the jar name along with the groupID, artificatID, and change the version type to SNAPSHOT.

DHS-53 Updated the jar name to a proper format.

---

README.md

Fixed spelling error :smiley:

---

Jenkinsfile
pom.xml

Added support for publishing OWASP scans and persisting via Jenkins pipeline

DHS-55 Added support for publishing OWASP scans and persisting via Jenkins pipeline

---

Jenkinsfile

Reverts CS-C-BDD-TDD/human-review-backend#12

Revert "Update Jenkinsfile remove sonar"

---

sonar-project.properties

Reverts CS-C-BDD-TDD/human-review-backend#18

Revert "Update sonar-project.properties"

---

src/main/java/gov/dhs/nppd/humanreview/service/UserApiController.java
src/test/java/gov/dhs/nppd/humanreview/service/UserApiControllerTest.java

DHS-39: Added unit tests for UserApiController

---

src/test/java/gov/dhs/nppd/humanreview/service/HumanreviewApiControllerTest.java

Please review new test coverage added to HumanReviewApiController

DHS-39-test added coverage test for HumanReviewApiController

---

README.md
pom.xml
src/main/resources/api.yaml
src/main/resources/application-dev.properties
src/main/resources/application-prod.properties
src/main/resources/application.properties

DHS-65 Updated new application.properties files to take in a environment variable for database specific settings depending on the current environment. Updated readme and adding api.yml file

Dhs 65 my sql connection

---

src/main/java/gov/dhs/nppd/humanreview/service/UserApiController.java

Updated the UserApiController by adding the @CrossOrigin notations to allow for CORS to work

DHS-66 CORS issue on UserApiController

---

src/main/resources/application-prod.properties

DHS-73 Updated the database hostname

---

src/main/java/gov/dhs/nppd/humanreview/service/HumanreviewApiController.java
src/main/java/gov/dhs/nppd/humanreview/service/UserApiController.java

DHS-73 Changed the UserApiController to return the correct status.

DHS-73 Changed the UserApiController to return the proper status.

---

src/main/resources/application-prod.properties

Changed the application-prod.properties to accept environment variables for the JDBC URL to the MySQL DB

DSH-73 Update applicatin-prod.properties

---

src/main/java/gov/dhs/nppd/humanreview/service/HumanreviewApiController.java
src/main/java/org/openapitools/api/HumanreviewApi.java
src/main/java/org/openapitools/model/HumanReviewItem.java
src/main/resources/application-prod.properties
src/main/resources/schema.sql

DHS-73 Added the humanreviewStixIdPost api to add records to the database.

Dhs 73 update review item

---

pom.xml

Added Changes to POM File ...
Requesting your approval ...

DHS-73: Added sonar.coverage.exclusions property to POM

---

src/main/java/gov/dhs/nppd/humanreview/service/HumanreviewApiController.java
src/main/java/org/openapitools/api/HumanreviewApi.java
src/main/java/org/openapitools/model/HumanReviewItem.java
src/main/java/org/openapitools/model/ListOfHumanReviewItems.java
src/main/java/org/openapitools/repository/HumanreviewRepository.java
src/main/java/org/openapitools/repository/JsonDataRepository.java
src/main/resources/data.sql
src/test/java/gov/dhs/nppd/humanreview/service/HumanreviewApiControllerTest.java

DHS-74 Completed the group update

Dhs 74 group update

---

src/main/java/org/openapitools/OpenAPI2SpringBoot.java
src/main/resources/api.yaml
src/main/resources/data.sql
src/test/java/gov/dhs/nppd/humanreview/sampledata/SampleDataTest.java

Please merge this branch to master. I added code to generate sample data for the stix. I also fixed the allow all headers

Allow all headers *; added sample data code

---

pom.xml
suppressedDependencyCVE.xml

Updated the project to ignore CVE for activemq client

Dhs 123 amq cvs error

---

README.md
src/main/java/org/openapitools/OpenAPI2SpringBoot.java
src/main/resources/application-dev.properties

Updated readme on how to setup a local AQM Server and removedcode that sent to queue on startup. Change applicatoin-dev to only use a local running amq server instead of embedded.

Dhs 124 using local amq server

---

Jenkinsfile

Added support for email notifications and reduced redudant mvn steps to speed build process

DHS-114: Added support for email notifications

---

Jenkinsfile

DHS-114: Refined so that build URL wouldn't have a newline, and added emails to distro

DHS-114: Refined so that build URL wouldn't have a newline

---

Jenkinsfile

DHS-114: Refined so that build URL wouldn't have a newline, and added emails to distro

DHS-114 updated language of email due to typo

---

README.md
src/main/java/gov/dhs/nppd/humanreview/service/HumanreviewApiController.java
src/main/java/gov/dhs/nppd/humanreview/util/JsonDocProcessor.java
src/test/java/gov/dhs/nppd/humanreview/service/HumanreviewApiControllerTest.java
src/test/java/gov/dhs/nppd/humanreview/util/JsonDocProcessorTest.java

DHS_120 AMQ added a delete after the Disseminate and fixed tests.

Dhs 120 amq update json

---

src/main/java/gov/dhs/nppd/humanreview/service/HumanreviewApiController.java

DHS-120 Amq fixed the format of returned json.

DHS-120 Amq fixed the format of returned json.

---

src/main/java/gov/dhs/nppd/humanreview/service/HumanreviewApiController.java
src/main/java/org/openapitools/repository/HumanreviewRepository.java
src/test/java/gov/dhs/nppd/humanreview/service/HumanreviewApiControllerTest.java

DHS-147 Fixed the update field to use field location instead of field name.

Dhs 147 fix update field

---

src/main/java/gov/dhs/nppd/humanreview/amq/Listener.java
src/main/java/gov/dhs/nppd/humanreview/amq/Sender.java
src/main/java/org/openapitools/OpenAPI2SpringBoot.java
src/main/resources/application-dev.properties
src/main/resources/application-test.properties

DHS-157 Switched AMQ to use topics instead of queues.

Dhs 157 switch to topic
